### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by David-Lanzz** [HERMON-1995/Web-development-capstone-project#2]
# Hello @HERMON-1995 🤗👋
- Correct use of GitHub flow🎈
- No linter Errors 🎈
- Task completion🎈
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a724d64453846675232357a676c6e6530712f67697068792e676966](https://user-images.githubusercontent.com/111298026/232728715-d02dd9b6-aeb8-43eb-b5ee-4030b95be3b6.gif)

You have a clean project here but there is just a little issue that needs fixing 😄

- I will suggest that unordered lists be used in the nav section instead of divs for a cleaner code and efficiency of screen readers😊

**Comment by HERMON-1995** [comment]
Thank you for your suggestion @David-Lanzz! I will refactor my code. 😊
